projetoBlog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


//Route::resource('/modelos', 'ModeloController');


Route::resource('/modelos', 'ModeloController',['except' =>['destroy']]);

Route::get('/modelos/{modelo}/delete', 'ModeloController@destroy')->name('modelos.destroy');












//Route::get('/modelos', 'ModeloController@index');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

projetoBlog/app/Models/Modelo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Modelo extends Model
{
    protected $fillable = [
        'modelo', 'status'
    ];
}

projetoBlog/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

projetoBlog/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

projetoBlog/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

projetoBlog/app/Http/Controllers/ModeloController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Modelo;

class ModeloController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $modelos = Modelo::all();
        return view('modelos.index')->with(['modelos' => $modelos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('modelos.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Modelo::create($request->all());

        return redirect()->route('modelos.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $modelo = Modelo::find($id);
        return view('modelos.show')->with(['modelo' => $modelo]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    $modelo = Modelo::find($id);
      return view('modelos.edit')->with(['modelo' => $modelo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $modelo = Modelo::find($id)->update($request->all());
        return redirect()->route('modelos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $modelo = Modelo::find($id)->delete();
        return redirect()->route('modelos.index');
    }
}

projetoBlog/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

projetoBlog/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('modelos.index')}}">{{ __('Modelos') }}</a>
                            </li>
                              <li class="nav-item">
                                <a class="nav-link" href="{{ route('modelos.create')}}">{{ __('Criar Modelos') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

projetoBlog/resources/views/modelos/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form action="{{route('modelos.store')}}" class="form-horizontal" method="POST"> 
    @csrf
    <div class="row">
        <label for="modelo"> Modelo do veículo </label>
        <input type ="text" id="modelo" name="modelo" class ="form-control"> 
    </div>
    <div class="row">
        <label for="status">Status </label>
        <input type ="text" id="status" name="status" class ="form-control"> 
    </div>
      <div class="row">
        
        <input type ="submit" class ="form-control" value ="Cadastrar">  
    </div>
    </form>
 </div>
@endsection

projetoBlog/resources/views/modelos/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form action="{{route('modelos.update',$modelo->id)}}" class="form-horizontal" method="POST"> 
    @csrf
    @method('PUT')
    <div class="row">
        <label for="modelo"> Modelo do veículo </label>
        <input type ="text" id="modelo" name="modelo" class ="form-control" value="{{old('modelo', $modelo->modelo)}}"> 
    </div>
    <div class="row">
        <label for="status">Status </label>
        <input type ="text" id="status" name="status" class ="form-control" value="{{old('modelo', $modelo->status)}}"> 
    </div>
      <div class="row">
        
        <input type ="submit" class ="form-control" value ="Atualizar">  
    </div>
    </form>
 </div>
@endsection

projetoBlog/resources/views/modelos/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <table class="table">
            <thead>
                <tr>
                <th scope="col">Id</th>
                <th scope="col">Modelo</th>
                <th scope="col">Status</th>
                 <th scope="col">Funções</th>
                </tr>
            </thead>
            <tbody>
              @foreach ($modelos as $modelo)
            <tr>
                <th scope="row"> {{$modelo->id}}</th>
                    <td>  Modelo:  {{$modelo->modelo}}</td>
                    <td>   Status: {{$modelo->status}} </td>
                    <td>
                        <a href="{{route('modelos.show',$modelo->id)}}">   Visualizar | </a>
                        <a href="{{route('modelos.edit',$modelo->id)}}"> Editar | </a>
                        <a href="{{route('modelos.destroy',$modelo->id)}}"> Deletar </a>
                    </td>
              
            </tr>
            @endforeach 
                </tbody>
        </table>

    </div>

@endsection

projetoBlog/resources/views/modelos/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

      {{$modelo->modelo}}
      {{$modelo->id}}

    </div>

@endsection